import Head from "next/head";
import About from "@/components/About";
import { useState } from "react";
import NavBar from "@/components/NavBar";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import { getPosts } from "@/api/gql";
import Blog from "@/components/Blog";

type Post = {
  title: string;
  brief: string;
  slug: string;
  _id: string;
};

export type Posts = { posts: Post[] };

export default function Home({ posts }: Posts) {
  const [visibleSection, setVisibleSection] = useState("");

  return (
    <>
      <Head>
        <title>Will Apolinário | Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar
        visibleSection={visibleSection}
        setVisibleSection={setVisibleSection}
      />
      <About />
      <hr className="border-gray-300 rounded border-1 max-w-md mx-auto" />
      <Skills />
      <hr className="border-gray-300 rounded border-1 max-w-md mx-auto" />
      <Projects />
      <hr className="border-gray-300 rounded border-1 max-w-md mx-auto" />
      <Blog posts={posts} />
    </>
  );
}

export async function getStaticProps() {
  const { posts } = await getPosts();

  return {
    props: {
      posts,
    },
  };
}
